### ISSUE TITLE
setting another audio output instead of the default 3,5mm jack

### ISSUE THREAD

**Issue by nikogusm** [home-assistant/plugin-audio#123]
hi guys, I have a problem: every time I restart Home Assistant, default audio output revert back to the 3,5mm jack output.
to make my audio card the default USB output again, I have to turn on my USB audio card, do a “ha audio reload” and after that I have to set up again the “ha audio default output” with the information that "pactl list" give me (they are always the same).

is there a way to automate it or save the default audio card that I set up every time?

**Comment by agners** [comment]
This is most likely addressed with #156. Please feel free to reopen if this is still an issue.
