### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by seancmalloy** [home-assistant/plugin-audio#155]
when i attempt to install aarch64-hassio-audio on my rpi4 (aarch64) via docker i receive unsupported media type application/vnd.dev.cosign.simplesigning.v1+json.  is rpi4 unsupported? this doesnt look like a valid ha addon repo, so how do i install it? any help appreciated, thanks

**Comment by agners** [comment]
The plug-ins are part of a Home Assistant Supervised installation, so this container is not meant to be installed manually.
