### ISSUE TITLE
Pulseaudio fails to restore original sample settings

### ISSUE THREAD

**Issue by NecrumBlack** [home-assistant/plugin-audio#167]
Hello, i'm having problems with pulseaudio on the hassio-audio image, every time I try to use the voice assist (wyoming protocol+ assist microphone+openwakeword+piper+whisper addons) or just piper using the Text-to-speech (TTS): Speak service trough the VLC-TELNET entity, the audio logs get spammed with this message until the memory runs out.

`PaltaHass hassio_audio[1543]: W: [alsa-sink-ff880000.i2s-ES8316 HiFi ES8316 HiFi-0] alsa-sink.c: Resume failed, couldn't restore original sample settings.`

what could be causing this?

thanks in advance
[ha audio info.txt](https://github.com/home-assistant/plugin-audio/files/14805253/ha.audio.info.txt)
[ha audio logs (before and after killing pulseaudio).txt](https://github.com/home-assistant/plugin-audio/files/14805254/ha.audio.logs.before.and.after.killing.pulseaudio.txt)
[ha info.txt](https://github.com/home-assistant/plugin-audio/files/14805255/ha.info.txt)
[pa-info (in hassio-audio)](https://github.com/home-assistant/plugin-audio/files/14807931/pa-info.in.hassio-audio.txt)

**Comment by NecrumBlack** [comment]
looking at module-alsa-sink.c i've found: 
```    if (!pa_sample_spec_equal(&ss, &u->sink->sample_spec)) {
        pa_log_warn("Resume failed, couldn't restore original sample settings.");
        goto fail;
    }
```
And the PA wiki says "This tests if the sample format specifications are identical."

Should I change somethink in order to make the hassio_audio container work properly?

**Comment by agners** [comment]
Most likely the driver or your platform doesn't support the sample rate TTS is trying to use :cry: 

Not sure what sample rate TTS is using. Have you tried playing sound directly with various sample rates on Debian on this platform (maybe you have to shutdown the Supervisor service and all containers to avoid conflicts). 

Did you try Home Assistant OS on that same platform? The ODROID-C2 is not all that well tested, so I am not sure if audio works on it :cry:

**Comment by agners** [comment]
Thanks for confirming. So yeah, this is a platform specific driver issue then :cry: 

I'd report this to the Orangepi 4 folks.

**Comment by NecrumBlack** [comment]
I'm not so sure, mostly because the TTS part works correctly if Spotify connect is playing music inside HA, and audio also works fine in baremetal, it's just when pulseaudio is connected through the hassio audio sock that fails to resume the sink.

**Comment by agners** [comment]
I guess it works correctly when Spotify is playing because then Pulseaudio mixes the two audio streams, and resamples TTS to whatever Spotify is using. To me it seems that the driver is advertising support for a sample rate (and Pulseaudio is trying to use it when only TTS is running) which it can't handle when trying to actually play it.

**Comment by NecrumBlack** [comment]
You were right all along (go figure!) after further testing with speaker-test, audio plays correctly at 44100Hz but breaks at 48000Hz.
Is there a way to configure pulseaudio inside the container/image to use a fixed sample rate? (non volatile config files?)

thanks for your patience

**Comment by agners** [comment]
No, currently we don't have such a "force baudrate option". In fact, i am not even sure if Pulseaudio has that. There is `default-sample-rate`, but I'd assume that Pulseaudio would also pick a higher sample rate if needed.

The problem here is really the audio driver advertises it is capable of 48000Hz. And Pulseaudio (correclty) makes use of it. As a simple fix, you probably can just delete that from the audio driver, but it really would need a kernel change.

**Comment by NecrumBlack** [comment]
In the end it was the Assist Microphone add-on who was causing all the playback issues, once deactivated, every sample rate works perfectly. Now i'm trying to know what's causing such problem, I'll post again if I find something.

**Comment by agners** [comment]
Maybe Assist Microphone plug-in uses an audio input which influences clocks of your audio output such that it can't run on those two different rates? :thinking:  What are your ALSA audio inputs (arecord -l)?

**Comment by NecrumBlack** [comment]
arecord -l
```
**** List of CAPTURE Hardware Devices ****                                                                                                                                                                       card 0: rockchipes8316c [rockchip-es8316c], device 0: ff880000.i2s-ES8316 HiFi ES8316 HiFi-0 [ff880000.i2s-ES8316 HiFi ES8316 HiFi-0]
Subdevices: 1/1                                                                                                                                                                                                  Subdevice #0: subdevice #0
```

arecord -L
`null                                                                                                                                                                                                                 `Discard all samples (playback) or generate zero samples (capture)                                                                                                                                            hw:CARD=rockchipes8316c,DEV=0                                                                                                                                                                                        rockchip-es8316c, ff880000.i2s-ES8316 HiFi ES8316 HiFi-0                                                                                                                                                         Direct hardware device without any conversions                                                                                                                                                               plughw:CARD=rockchipes8316c,DEV=0                                                                                                                                                                                    rockchip-es8316c, ff880000.i2s-ES8316 HiFi ES8316 HiFi-0                                                                                                                                                         Hardware device with all software conversions                                                                                                                                                                default:CARD=rockchipes8316c                                                                                                                                                                                         rockchip-es8316c, ff880000.i2s-ES8316 HiFi ES8316 HiFi-0                                                                                                                                                         Default Audio Device                                                                                                                                                                                         sysdefault:CARD=rockchipes8316c                                                                                                                                                                                      rockchip-es8316c, ff880000.i2s-ES8316 HiFi ES8316 HiFi-0                                                                                                                                                         Default Audio Device                                                                                                                                                                                         dsnoop:CARD=rockchipes8316c,DEV=0                                                                                                                                                                                    rockchip-es8316c, ff880000.i2s-ES8316 HiFi ES8316 HiFi-0                                                                                                                                                         Direct sample snooping device`
