### ISSUE TITLE
Failed to load cookie file from cookie

### ISSUE THREAD

**Issue by jsells02** [home-assistant/plugin-audio#22]
I am seeing this issue again with HA: 0.108.3 / Supervisor: 217
It was previously reported under #10 and supposedly fixed and closed under #5.

20-04-14 12:46:33 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
Failed to load cookie file from cookie: No such file or directory

**Comment by pvizeli** [comment]
Just a log, no issue
