### ISSUE TITLE
Ubuntu 20.04 Firefox FlashPlayer

### ISSUE THREAD

**Issue by LucaEstiva** [home-assistant/plugin-audio#24]
Ubuntu 20.04 Desktop ( development workstation )
Docker installed with: sudo apt install docker.io  ( https://linuxconfig.org/how-to-install-docker-on-ubuntu-20-04-lts-focal-fossa )

All the container is running with no problem ( Home Assistant installed with installer.sh ) but if the container:

sudo docker container ls -a

homeassistant/amd64-hassio-audio:14             "/init"                  52 seconds ago      Up 51 seconds                           hassio_audio

is running, the flash player plugins doesn't work. Stop the container solve the problem... Thanks...

**Comment by pvizeli** [comment]
Not supported
