### ISSUE TITLE
load-module module-bluetooth-discover

### ISSUE THREAD

**Issue by zhujisheng** [home-assistant/plugin-audio#31]
Since there's [`bluetoothctl` in hassos](https://github.com/home-assistant/operating-system/blob/dev/Documentation/bluetooth.md), I think the pulseaudio should `load-module module-bluetooth-discover` when start up.

**Comment by pvizeli** [comment]
Yeah, but I have currently not the time to test it and maybe fix some small issues around this

**Comment by zhujisheng** [comment]
I have manually load this module, and it works right when a bluetooth speaker connects.

And I'm programming [a media_player integration based on pulseaudio](https://github.com/zhujisheng/HAComponent/tree/master/pulseaudio), which have no need to install add-ons under hassio like vlc or mpd.
If there's bluetooth devices in pulseaudio，it will be more powerful.

**Comment by pvizeli** [comment]
Feel free to provide an PR 👍

**Comment by zhujisheng** [comment]
I know exactly that what should do is only append the file [`/etc/pulse/system.pa`](https://github.com/home-assistant/plugin-audio/blob/master/rootfs/etc/pulse/system.pa) with:
```
load-module module-bluetooth-discover
```

But I don't know how to build and test this project, and which branch to PR.

**Comment by zhujisheng** [comment]
Besides, I think it should `load-module module-detect`, so that the usb mic and speaker can be detected at once, no need to restart the hassio_audio docker.
I'm not sure about this.

**Comment by pvizeli** [comment]
> module-detect

Not really, this module is deprecated.
