### ISSUE TITLE
hassio_audio proper log handling, less spamming

### ISSUE THREAD

**Issue by JJFourie** [home-assistant/plugin-audio#57]
## Problem    

The ```hassio_audio``` container continuously outputs info and debug data, that puts unnecessary load on downstream systems and contribute to reducing the lifespan of SD's / SSD's.
It is not possible (to my knowledge) to set the log level for ```hassio_audio```. It does not seem to support the Home Assistant standard that allows the log level to be set in the Logger Integration in ```configuration.yaml```, as explained in the [Logger documentation](https://www.home-assistant.io/integrations/logger).

## Request    

1) Remove the ```-vvv``` PulseAudio run parameter, to make the output less verbose. Or make it configurable.
2) Add a timestamp to the PulseAudio messages ```--log-time[=BOOL]```
3) Set the correct level for stdout / stderr messages raised to journald. Currently ALL ```hassio_audio``` messages are raised as level 3 (i.e. error), whether "D" (debug), "I" (info), or "E" (error).
4) Support the Logger directive to allow the user to set the output log level, e.g. critical / error / info / debug.    
   Maybe this can be achieved using the "--log-level" PulseAudio command parameter? 

#### Home Assistant logger filter setting has no effect on ```hassio_audio```

Current logger settings in ```configuration.yaml```.
```
logger:
  default: critical
  logs:
    homeassistant.core: fatal
```

Even with the log settings above, below are typical "D" (debug) and "I" (info) messages output by ```hassio_audio```, retrieved from the Docker logs for the container. The "critical" default setting has no effect on the filtering of messages from ```hassio_audio```. Or is there an (undocumented) setting that actually works to filter only real error messages?

```
docker logs audio_hassio
...
I: [pulseaudio] client.c: Created 14 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
D: [pulseaudio] protocol-native.c: Protocol version: remote 34, local 34
D: [pulseaudio] protocol-native.c: SHM possible: no
D: [pulseaudio] protocol-native.c: Negotiated SHM: no
D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
I: [pulseaudio] client.c: Freed 14 "supervisor"
I: [pulseaudio] protocol-native.c: Connection died.
...

```
#### ```hassio_audio``` raises ALL messages as errors, regardless of their real level.

Below are the same ```hassio_audio``` log records, this time retrieved using journalctl.
NOTE: 
- In the journalctl command below **only errors were retrieved** (parameter ```-p err```).
- The messages returned from journalctl are information ("I") and debug ("D") level messages, but with an error log level.

```
journalctl CONTAINER_NAME=hassio_audio -p err

-- Logs begin at Mon 2021-03-08 22:43:29 CET, end at Sat 2021-03-13 12:44:51 CET. --
...
Mar 10 00:05:12 RPiHome 5941937722e7[584]: I: [pulseaudio] client.c: Created 14 "Native client (UNIX socket client)"
Mar 10 00:05:12 RPiHome 5941937722e7[584]: I: [pulseaudio] protocol-native.c: Client authenticated anonymously.
Mar 10 00:05:12 RPiHome 5941937722e7[584]: D: [pulseaudio] protocol-native.c: Protocol version: remote 34, local 34
Mar 10 00:05:12 RPiHome 5941937722e7[584]: D: [pulseaudio] protocol-native.c: SHM possible: no
Mar 10 00:05:12 RPiHome 5941937722e7[584]: D: [pulseaudio] protocol-native.c: Negotiated SHM: no
Mar 10 00:05:12 RPiHome 5941937722e7[584]: D: [pulseaudio] protocol-native.c: Disabling srbchannel, reason: No SHM support
Mar 10 00:05:12 RPiHome 5941937722e7[584]: I: [pulseaudio] client.c: Freed 14 "supervisor"
Mar 10 00:05:12 RPiHome 5941937722e7[584]: I: [pulseaudio] protocol-native.c: Connection died.
...
```

And the first record from the above output, now shown verbose to confirm ```PRIORITY=3```:

```
journalctl CONTAINER_NAME=hassio_audio --since "2021-03-10 00:05:00" --until "2021-03-10 00:06:00" -o verbose

-- Logs begin at Mon 2021-03-08 22:43:29 CET, end at Sat 2021-03-13 12:44:51 CET. --
Wed 2021-03-10 00:05:12.194229 CET [s=e0ae8b76d4cd495caeca4d33ba3702ea;i=2ba;b=285f795042f04f8588bbdd5ce295afd7;m=15418de86b;t=5bd22952310d4;x=37ce5b2c89d83e4]
    _BOOT_ID=285f795042f04f8588bbdd5ce295afd7
    _MACHINE_ID=be042b18af4b495ca4957bfef9e53bfd
    _HOSTNAME=RPiHome
    _UID=0
    _GID=0
    _SYSTEMD_SLICE=system.slice
    _TRANSPORT=journal
    _CAP_EFFECTIVE=1ffffffffff
    PRIORITY=3
    _PID=584
    _COMM=dockerd
    _EXE=/usr/bin/dockerd
    _CMDLINE=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
    _SYSTEMD_CGROUP=/system.slice/docker.service
    _SYSTEMD_UNIT=docker.service
    _SYSTEMD_INVOCATION_ID=02eb6c5d4ad24576bd16a7252e7c8803
    CONTAINER_NAME=hassio_audio
    CONTAINER_TAG=5941937722e7
    IMAGE_NAME=homeassistant/armv7-hassio-audio:2021.02.1
    SYSLOG_IDENTIFIER=5941937722e7
    CONTAINER_ID=5941937722e7
    CONTAINER_ID_FULL=5941937722e730a3f0045de4a539addcca6209c9ef10d227499d2d843bebe0e0
    MESSAGE=I: [pulseaudio] client.c: Created 14 "Native client (UNIX socket client)"
    _SOURCE_REALTIME_TIMESTAMP=1615331112194229
...
```

**Comment by JJFourie** [comment]
Regarding request (3): *"Set the correct log level for stdout / stderr messages raised to journald. Currently ALL hassio_audio messages are raised as level 3 (i.e. error), whether "D" (debug), "I" (info), or "E" (error)."*

I just want to confirm that Docker **does** support logging ```stdout``` and ```stderr```](https://docs.docker.com/config/containers/logging/) as different log levels in journald. 
- The ```stdout``` stream is logged with priority 6, which is the LINUX level for "information".
- The ```stderr``` stream is logged with priority 3, which is the LINUX level for "error".

Do the following quick test to verify that Docker will assign different priorities to STDOUT and STDERR messages:
1) Connect and run a Bash shell in the ```hassio_audio``` container.
2) Output test messages to both ```stdout``` and ```stderr``` (using the stream of the process running as PID 1).
3) Confirm the priority of the two messages that were logged in journal, using journalctl.

```
# Connect as Bash, then send messages to both stderr and stdout.

docker exec -it hassio_audio bash
bash-5.1#
bash-5.1# echo "TESTING STDERR" >> /proc/1/fd/2
bash-5.1# echo "TESTING STDOUT" >> /proc/1/fd/1
bash-5.1#
bash-5.1# exit
 
---

# Search journalctl for all hassio_audio messages logged in the past hour, containing "TESTING" in the message.

journalctl CONTAINER_NAME=hassio_audio -S -1h | grep "TESTING"

---

# Search journalctl for all hassio_audio messages logged with PRIORITY 6 (i.e. log level "information"):
# (The "TESTING STDOUT" message should be in the output.)

journalctl CONTAINER_NAME=hassio_audio PRIORITY=6

---

# Verify the priority of the two "TESTING.." messages in the log detail.

journalctl CONTAINER_NAME=hassio_audio -S -1h  -o verbose

```

**Comment by luka6000** [comment]
please, can you do something about it? This thing is logging like crazy and I don't even have audio enabled on pi.

**Comment by JJFourie** [comment]
@luka6000  As a workaround you could consider to implement [this shell script](https://github.com/JJFourie/HomeAssistant-PulseAudio-Disable). Or you can borrow the idea/adjust the shell script and do something yourself.
The key thing that it does is to change the PulseAudio run parameters inside the `hassio_pulseaudio` container after the container (re)started, then kill PulseAudio. PulseAudio will automatically be restarted, with the new parameters, and now only log error level messages (including a log timestamp).

These are the Docker commands executed from the host OS:
```
# update the PulseAudio parameters in the run file in the hassio_audio container:
docker exec -i hassio_audio sed -i 's/-vvv/--log-level=0 --log-time=true/' /run/s6/services/pulseaudio/run

# stop PulseAudio in the hassio_audio container:
docker exec -i hassio_audio pkill pulseaudio
```

**Comment by tylerszabo** [comment]
I just got a disk space warning that I chased down to 4GB of exactly this. I'm surprised that this issue has been open for so long.

**Comment by tylerszabo** [comment]
Is there a way to disable this pugin entirely? My Home Assistant is running on a headless machine that does no audio processing.

I don't think I need to label the graph to show the point at which the plugin started to cause issues with log size
![image](https://user-images.githubusercontent.com/315343/132069131-d3d56a1e-f027-41e4-abf8-db35a7c172e3.png)

**Comment by tylerszabo** [comment]
Added pull request #85
