### ISSUE TITLE
no soundcards available to choose, only default...

### ISSUE THREAD

**Issue by raph2i** [home-assistant/plugin-audio#6]
... but on system/hardware there is my usb-soundcard listed. (This is with Synology DSM, yes, you wont support it, its ok)

```
audio:

    0:
        name: USB-Audio - Jabra SOLEMATE v1.34.0
        type: v1340
        devices:
            [object Object]
            [object Object]
```
But on an normal Home Assistant installation on Debian Buster with Docker, the same issue exists.

```
audio:

    0:
        name: HDA-Intel - HDA Intel
        type: Intel
        devices:
            [object Object]
            [object Object]
            [object Object]
            [object Object]
            [object Object]

```

What exactly changed in the last week?

**Comment by raph2i** [comment]
Maybe this is part of the issue:
`2020/03/04 23:13:03 socat[369] E connect(5, AF=1 "/data/internal/pulse.sock", 27): No such file or directory`

**Comment by pvizeli** [comment]
Because PulseAudio did not detect you sound card. With new CLI >= 4.1 you can use `ha audio logs` to see what is going on. Maybe you can find on google what you need exactly for files to make it running on Linux/Pulse. This changes can be applay to this repository and we can destribute it 👍

**Comment by pvizeli** [comment]
By the way, not support synology did not mean that we not help troubleshooting and merge PR they fix issue on that platform. It means only that we not active fix bug and this part need comes from the maintainer of that community installation.

**Comment by raph2i** [comment]
Hi @pvizeli, Supervisor Version 207 / Update Core 106.4 breaks it. 
Here are the logs: https://gist.github.com/raph2i/e74b0948970a9bb1ae2d8fe6db58cd49
It worked like a charm before the update.

I don't understand what has changed, and how the "chain" works?

/dev/snd is mounted via a bind mount into hassio_supervisor and then to hassio_audio?
Has pulseaudio to be running in the underlying OS?

**Comment by Maco65** [comment]
I think in my case ( https://github.com/home-assistant/audio/issues/7 ) it was also 106.4 upade which made the problem.

**Comment by jyz0501** [comment]
https://github.com/home-assistant/supervisor/issues/1582  
I have a error  like this~

**Comment by pvizeli** [comment]
Should be solve with latest container
