### ISSUE TITLE
USB Sound card does not appear in HA

### ISSUE THREAD

**Issue by philibertc** [home-assistant/plugin-audio#74]
### The problem

When a sound card is connected, it appears well when `dmesg` is run but does not appear anywhere on HA (Audio Add-ons, `ha audio info`).

### What is version of Home Assistant Core has the issue?

core-2021.4.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

system

### Anything in the logs that might be useful for us?

```txt
`ha audio logs` output:
https://imgur.com/a/K9nddQg
I can't copy the text inside the terminal add-on.
```

**Comment by pvizeli** [comment]
looks good, you don't see it with `ha audio info`?

**Comment by philibertc** [comment]
> looks good

@pvizeli No, there are many ”Connexion Died”.

> you don’t see it with `ha audio info`?

No, there is only the Dummy Output.

**Comment by philibertc** [comment]
> I assume this is Home Assistant OS in a virtual machine?

@agners Yes.

**Comment by philibertc** [comment]
> ```
>   card:
>   - driver: module-alsa-card.c
>     index: 0
>     name: alsa_card.usb-Generic_USB_Audio_201405280001-00
> ```
@balloob Does I need to add this in configuration.yaml?

**Comment by balloob** [comment]
No. This is output of `ha audio info`.

**Comment by philibertc** [comment]
> No. This is output of `ha audio info`.

@balloob Okay. I have :
![image](https://user-images.githubusercontent.com/57588282/118251899-724bae80-b4a8-11eb-8741-8a01e7dbba39.png)

**Comment by philibertc** [comment]
I've opened a clean and precise issue #77
