### ISSUE TITLE
Cannot play sound from Hassos on VBOX

### ISSUE THREAD

**Issue by vandad51** [home-assistant/plugin-audio#92]
I'm a bit green to HA so bare with me. I'm using browser mod to start doing sound notifications and I cannot seem to get any sound from any device I use. [In my audio logs,](https://pastebin.com/km25DcNR) at the bottom, when I try to use TTS it shows that it's tried, but I don't know what it means.

I followed [the home assistant installation instructions](https://www.home-assistant.io/installation/windows) to install it in my Windows 10 machine using Vbox.

Here's my system health page:

Version | core-2021.11.5
Installation Type | Home Assistant OS
HASSOS | 6.6
Supervisor | 2021.12.1
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.75
CPU Architecture | x86_64

This is what I see when I try find something through ssh.

ha audio 
audio:
  application: []
  card: []
  input: []
  output:
  - applications: []
    card: null
    default: true
    description: Dummy Output
    index: 0
    mute: false
    name: auto_null
    volume: 1
host: 172.30.32.4
update_available: false
version: 2021.07.0
version_latest: 2021.07.0

Any help is appreciated!

**Comment by agners** [comment]
This is not a plugin-audio issue as the OS provides no Audio controller. For VirtualBox its crucial that you choose "Intel HD Audio" as Audio Controller. I created a PR to fix the instructions: https://github.com/home-assistant/home-assistant.io/pull/20708/files.
